name: CI - Molecule Tests

on:
  pull_request:
  push:

jobs:
  molecule:
    name: Molecule Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        docker_img_distro:
          - "debian:bookworm"
          - "ubuntu:24.04"

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v5
        with:
          path: '16x7.firewall'

      - name: Set up Python 3.
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Upgrade pip
        shell: bash
        run: python -m pip install --upgrade pip

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/molecule/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install test dependencies.
        shell: bash
        run: pip3 install -r 16x7.firewall/molecule/requirements.txt

      - name: Run Molecule tests.
        working-directory: 16x7.firewall
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DOCKER_IMG_DISTRO: ${{ matrix.docker_img_distro }}
        shell: bash
        run: molecule test